In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [3]:
type(a)

numpy.ndarray

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


 - [] - ONE  D
 - [[] , []] - TWO D
 - [[[],[]] ,[[],[]]] - THREE D

In [6]:
x = np.array([[1,2],[3,4]])
print(x)
type(x)

[[1 2]
 [3 4]]


numpy.ndarray

In [7]:
print(x.shape)

(2, 2)


In [8]:
print(x.ndim)

2


In [9]:
print(x.dtype)

int64


[[[3, 4], [4, 5]], [[1, 2], [7, 9]]]


In [22]:
np.random.randint(10,40, size=(3,5))

array([[26, 36, 36, 24, 24],
       [33, 31, 29, 26, 11],
       [24, 10, 15, 21, 17]])

In [36]:
x = np.array([[1,4,6] ,[4,5,7] , [8,7,4]])
y = np.array([[2,9,0] ,[9,5,2] , [10,12,13]])
print(x)
print(y)

[[1 4 6]
 [4 5 7]
 [8 7 4]]
[[ 2  9  0]
 [ 9  5  2]
 [10 12 13]]


In [29]:
print(x*y)

[[ 2 36  0]
 [36 25 14]
 [80  0 52]]


In [32]:
print(x@y)
print(x.dot(y))

[[ 98 101  86]
 [123 145 101]
 [ 56 120  52]]
[[ 98 101  86]
 [123 145 101]
 [ 56 120  52]]


In [37]:
x.prod()

np.int64(752640)

In [38]:
x.sum()

np.int64(46)

In [39]:
x.mean()

np.float64(5.111111111111111)

In [40]:
x.mean(axis=0) #column wise mean
y.mean(axis=1) #row wise mean

array([ 3.66666667,  5.33333333, 11.66666667])

In [41]:
x.max()

np.int64(8)

In [42]:
x.min()

np.int64(1)

In [43]:
x.argmax()

np.int64(6)

In [47]:
z = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.percentile(z,25))
print(np.percentile(z,50))
print(np.percentile(z,75))



3.25
5.5
7.75


In [50]:
arr = np.array(([1,2,3,4],[4,3,5,7],[4,67,12,31],[4,6,7,8]))
print(arr)

[[ 1  2  3  4]
 [ 4  3  5  7]
 [ 4 67 12 31]
 [ 4  6  7  8]]


In [57]:

print(arr.reshape(2,8))
print(arr.reshape(8,2))


[[ 1  2  3  4  4  3  5  7]
 [ 4 67 12 31  4  6  7  8]]
[[ 1  2]
 [ 3  4]
 [ 4  3]
 [ 5  7]
 [ 4 67]
 [12 31]
 [ 4  6]
 [ 7  8]]
